# Generated by Django 3.0.6 on 2020-05-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDName', models.CharField(max_length=100)),
                ('PRDDesc', models.TextField()),
                ('PROPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('PROCost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('PROCreated', models.DateTimeField()),
            ],
        ),
    ]
