# Generated by Django 3.0.6 on 2020-05-25 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200525_1854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_Accessories',
        ),
        migrations.AlterModelOptions(
            name='product_alternative',
            options={'verbose_name': 'Product Alternative', 'verbose_name_plural': 'Product Alternatives'},
        ),
        migrations.AlterField(
            model_name='category',
            name='CATDesc',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATImg',
            field=models.ImageField(upload_to='category/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATName',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATParent',
            field=models.ForeignKey(blank=True, limit_choices_to={'CATParent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name='Main Category'),
        ),
        migrations.AlterField(
            model_name='product_alternative',
            name='PALTAlternatives',
            field=models.ManyToManyField(related_name='alternative_prducts', to='product.Product', verbose_name='Alternations'),
        ),
        migrations.AlterField(
            model_name='product_alternative',
            name='PALTProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_prduct', to='product.Product', verbose_name='Product'),
        ),
    ]
