# Generated by Django 3.0.6 on 2020-05-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_accessories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_accessories',
            options={'verbose_name': 'Product Accessory', 'verbose_name_plural': 'Product Accessories'},
        ),
    ]
