# Generated by Django 3.0.6 on 2020-05-26 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_variant'),
        ('product', '0010_auto_20200525_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PROBrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='PROCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category'),
        ),
    ]
