# Generated by Django 3.0.6 on 2020-05-27 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20200527_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='PROCost',
            new_name='PRDCost',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='PROCreated',
            new_name='PRDCreated',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='PROPrice',
            new_name='PRDPrice',
        ),
    ]
